name: UnitTest

on:
  push:
    branches: [v5]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  test-linux:
    name: "ubuntu-18"
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: |
          echo "Working directory: `pwd`"
          echo "Node version: `node --version`"
          echo "Npm version: `npm --version`"
          echo "Yarn version: `yarn --version`"
          yarn --non-interactive install
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Build
        run: |
          make prepare
          make build
      - name: Install Playwright
        run: npx playwright install --with-deps chromium firefox
      - name: Run tests
        run: npx jest --coverage --runInBand --detectOpenHandles

  test-mac:
    name: "mac"
    strategy:
      fail-fast: false
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: |
          echo "Working directory: `pwd`"
          echo "Node version: `node --version`"
          echo "Npm version: `npm --version`"
          echo "Yarn version: `yarn --version`"
          yarn --non-interactive install
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Build
        run: |
          make prepare
          npx vite build --mode production --config config/vite.prod.ts
          npx vite build --mode production --config config/vite.serverEntry.ts
          npx vite build --mode production --config config/vite.server.ts
      - name: Install Playwright
        run: npx playwright install --with-deps chromium firefox
      - name: Run tests
        run: npx jest --coverage --runInBand --detectOpenHandles

  test-windows:
    name: "Windows"
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: |
          echo "Working directory: `pwd`"
          echo "Node version: `node --version`"
          echo "Npm version: `npm --version`"
          echo "Yarn version: `yarn --version`"
          yarn --non-interactive install
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Build
        run: |
          make prepare
          npx vite build --mode production --config config/vite.prod.ts
          npx vite build --mode production --config config/vite.serverEntry.ts
          npx vite build --mode production --config config/vite.server.ts
      - name: Install Playwright
        run: npx playwright install --with-deps chromium firefox
      - name: Run tests
        run: npx jest --coverage --runInBand --detectOpenHandles
